version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
      ExternalCatalogBaseUrl: http://localhost:6083
    ports:
      - "6083:80"
    container_name: eventcatalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

 
  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: webshop
    environment:
      CatalogUrl: http://catalog
      ASPNETCORE_ENVIRONMENT: Development
        
    ports:
      - "52802:80"
    networks:
      - frontend
    depends_on:
      - catalog
     
   
  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    container_name: eventsqlserver
    ports:
      - "1453:1433"
    networks:
      - backend
